version: '3.8'
services:
    db:
        image: postgres:14.4-alpine
        restart: always
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=my-secret-pw@
            - POSTGRES_DB=slack-clone-api
        volumes: 
            - db:/var/lib/postgresql/data
    redis:
        image: redis:7.0.4-alpine
        restart: always
        container_name: redis
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "my-secret-pw@"]
        ports:
            - '6379:6379'
        volumes:
            - redisdb:/var/lib/redis
volumes:
  db:
  redisdb: