version: '3.9'
services:
    db:
        image: postgres:16.0-alpine
        restart: always
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=my-secret-pw@
            - POSTGRES_DB=slack-clone-api
        volumes: 
            - ./volumes/db-data:/var/lib/postgresql/data
            - ./seeds/sql/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql:ro
    redis:
        image: redis:7.2.3-alpine3.18
        restart: always
        container_name: redis
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "my-secret-pw@"]
        ports:
            - '6379:6379'
        volumes:
            - ./volumes/redisdb-data:/var/lib/redis